language: node_js
dist: trusty
sudo: required
script: npm run travis
node_js:
  - 0.10
  - 0.12
  - 4.2.4
  - 4.4
  - 6

before_install:
  - sudo apt-get install python-software-properties
  - sudo add-apt-repository -y ppa:ondrej/pkg-gearman
  - sudo apt-get update
  - sudo apt-get install gearman
  - gearmand -V
